version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/cointrack_db
      - BACKEND_CORS_ORIGINS=["http://127.0.0.1:8002","http://127.0.0.1:8080"]
    ports:
      - "8002:8002"

  db:
    image: postgres:14  # https://hub.docker.com/_/postgres
    ports:
      - "5433"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cointrack_db
volumes:
  app-db-data:
