"""Create tables

Revision ID: ae1035ac9c8f
Revises: 24fb512b2527
Create Date: 2021-11-26 02:50:36.519490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1035ac9c8f'
down_revision = '24fb512b2527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
