"""My migrations

Revision ID: e43c3dde70af
Revises: ae1035ac9c8f
Create Date: 2021-11-26 14:06:29.080328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43c3dde70af'
down_revision = 'ae1035ac9c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_index(op.f('ix_currency_label'), 'currency', ['label'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('coinprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=128), nullable=True),
    sa.Column('currency_label', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('current_datetime', sa.DateTime(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_label'], ['currency.label'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coinprice_currency_label'), 'coinprice', ['currency_label'], unique=False)
    op.create_index(op.f('ix_coinprice_id'), 'coinprice', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coinprice_id'), table_name='coinprice')
    op.drop_index(op.f('ix_coinprice_currency_label'), table_name='coinprice')
    op.drop_table('coinprice')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_currency_label'), table_name='currency')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
