"""First migration

Revision ID: cfdc4fc17aa7
Revises: fef97c2e263d
Create Date: 2022-07-03 19:37:01.173621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdc4fc17aa7'
down_revision = 'fef97c2e263d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.drop_column('user', 'email')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
